version: '3'
services:
  sql:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    hostname: sql
